spring:
  application:
    name: ecommerce
  server:
    port: 8090
# H2 Database
  datasource:
    url: jdbc:h2:mem:devDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
# H2 console
  h2:
    console:
      enabled: true
      path: /h2-console
# Hibernate
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# log level
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: TRACE

  
# jwt
service:
  jwt:
    token-type: Bearer
    key: c0h-5G2yWGA3hfjdrTQIU_xfWa_JLRvnfzTKdbcQ4bJj3CuSHczMq-NvgfQ4cAYkdNfCWwqQy_f5BNfidSGlNw==
    access-expiration: 36000000
    refresh-expiration: 864000000
